apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
  - name: argo-cd
    includeCRDs: true
    version: 7.6.2
    repo: https://argoproj.github.io/argo-helm
    valuesFile: files/argocd.values.yaml
    releaseName: appliance
resources: 
- namespace.yaml











